from datetime import datetime

class AIAssessment:
    """
    AIAssessment entity mapping to Figure 4.3 Class Diagram and Figure 4.5 Database Schema.
    Stores automated inference outcomes generated by SSD-MobileNetV2.
    """
    SEVERITY_LOW = 'Low'
    SEVERITY_MEDIUM = 'Medium'
    SEVERITY_CRITICAL = 'Critical'

    CLASS_CRACK = 'Crack'
    CLASS_POTHOLE = 'Pothole'
    CLASS_SURFACE_DETERIORATION = 'Surface Deterioration'

    def __init__(self, image_id, defect_class, confidence_score, bounding_box, relative_severity,
                 detections=None, assessment_id=None, model_name='SSD-MobileNetV2', created_at=None):
        self.assessment_id = str(assessment_id) if assessment_id else None
        self.image_id = str(image_id)
        self.defect_class = defect_class  # Primary defect category
        self.confidence_score = round(float(confidence_score), 4)
        self.bounding_box = bounding_box  # [ymin, xmin, ymax, xmax] normalized (0 to 1)
        self.relative_severity = relative_severity  # 'Low', 'Medium', 'Critical'
        self.detections = detections or []  # All detected instances in the image
        self.model_name = model_name
        self.created_at = created_at or datetime.utcnow().isoformat()

    def to_dict(self):
        return {
            'assessment_id': self.assessment_id,
            'image_id': self.image_id,
            'defect_class': self.defect_class,
            'confidence_score': self.confidence_score,
            'bounding_box': self.bounding_box,
            'relative_severity': self.relative_severity,
            'detections': self.detections,
            'model_name': self.model_name,
            'created_at': self.created_at
        }

    @classmethod
    def from_dict(cls, data):
        if not data:
            return None
        return cls(
            assessment_id=data.get('_id') or data.get('assessment_id'),
            image_id=data.get('image_id'),
            defect_class=data.get('defect_class', 'Crack'),
            confidence_score=data.get('confidence_score', 0.0),
            bounding_box=data.get('bounding_box', [0, 0, 0, 0]),
            relative_severity=data.get('relative_severity', cls.SEVERITY_LOW),
            detections=data.get('detections', []),
            model_name=data.get('model_name', 'SSD-MobileNetV2'),
            created_at=data.get('created_at')
        )
